[package]
name = "shami_rs"
version = "0.1.0"
edition = "2021"
authors = ["Euan Deas"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.12"
